import fs from 'fs';
import path from 'path';

const CHARACTERS_URL = 'https://raw.githubusercontent.com/EnkaNetwork/API-docs/master/store/characters.json';
const LOC_URL = 'https://raw.githubusercontent.com/EnkaNetwork/API-docs/master/store/loc.json';
const OUTPUT_PATH = path.join(process.cwd(), 'src/data/localization.ts');

async function main() {
    console.log('Fetching characters...');
    const charsParams = { method: 'GET' };
    const charsRes = await fetch(CHARACTERS_URL, charsParams);
    const charsData = await charsRes.json();

    console.log('Fetching localization data...');
    const locParams = { method: 'GET' };
    const locRes = await fetch(LOC_URL, locParams);
    const locData = await locRes.json();

    const enMap = locData.en;
    // Try 'ja' or 'jp', usually 'ja' in Enka/Genshin data structure, but let's check
    const jpMap = locData.ja || locData.jp;

    if (!jpMap) {
        console.error('Could not find Japanese localization data (checked "ja" and "jp"). Available keys:', Object.keys(locData));
        process.exit(1);
    }

    const characterMap = {};
    const reverseMap = {};

    console.log('Processing characters...');
    for (const [id, charInfo] of Object.entries(charsData)) {
        const hash = charInfo.NameTextMapHash;
        if (!hash) continue;

        const enName = enMap[hash];
        const jpName = jpMap[hash];

        if (enName && jpName) {
            characterMap[enName] = jpName;
            reverseMap[jpName] = enName;
        }
    }

    // Element and Weapon Map (Static for now, or could delve into other stores, but static is safer/faster for small sets)
    const manualMaps = `
export const ELEMENT_MAP: Record<string, string> = {
  'Pyro': '炎',
  'Hydro': '水',
  'Anemo': '風',
  'Electro': '雷',
  'Dendro': '草',
  'Cryo': '氷',
  'Geo': '岩',
  'None': '物理', // Sometimes needed
};

export const WEAPON_MAP: Record<string, string> = {
  'WEAPON_SWORD_ONE_HAND': '片手剣',
  'WEAPON_CLAYMORE': '両手剣',
  'WEAPON_POLE': '長柄武器',
  'WEAPON_BOW': '弓',
  'WEAPON_CATALYST': '法器',
};

export const ROLE_MAP: Record<string, string> = {
  'Main DPS': 'メイン火力',
  'Sub DPS': 'サブ火力',
  'Support': 'サポート',
  'Healer': 'ヒーラー',
};
`;

    const fileContent = `// Auto-generated by scripts/update_localization.mjs
// Data source: EnkaNetwork API

${manualMaps}

export const CHARACTER_MAP: Record<string, string> = ${JSON.stringify(characterMap, null, 2)};

export const REVERSE_CHARACTER_MAP: Record<string, string> = ${JSON.stringify(reverseMap, null, 2)};
`;

    // Ensure directory exists (src/data might theoretically not exist if I didn't create it, but I did)
    // fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

    fs.writeFileSync(OUTPUT_PATH, fileContent);
    console.log(`Successfully generated localization data at ${OUTPUT_PATH}`);
    console.log(`Mapped ${Object.keys(characterMap).length} characters.`);
}

main().catch(err => {
    console.error('Error updating localization:', err);
    process.exit(1);
});
